version: "3.8"

services:
  db:
    container_name: mysql_db
    image: mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      omega_network:
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: unless-stopped

  # Database management tool
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      omega_network:
    restart: unless-stopped

networks:
  omega_network: